In [1]:
import datalair
from pathlib import Path
import anndata as ad
import numpy as np
import pandas as pd
import singlecellrnasignature
import pyensembl
from icir._utils import normalize_all_genes

# storage_path = Path("/storage/halu").resolve()
storage_path = Path("/Users/halu/remote_connections/olm/storage/halu").resolve()
assert storage_path.exists()
lair = datalair.Lair(storage_path / "lair")
lair.assert_ok_satus()

ModuleNotFoundError: No module named 'datalair'

In [6]:
ds = singlecellrnasignature.adata.AziziSingleCellMapDiverse2018Adata()
lair.safe_derive(ds, overwrite=False)

In [9]:
adatas_matrix = list()
adatas_counts = list()
ds = singlecellrnasignature.adata.AziziSingleCellMapDiverse2018Adata()
for filepath in sorted(list(lair.get_dataset_filepaths(ds).values())):
    if filepath.name[0] == ".":
        continue
    adata = ad.read_h5ad(filepath)
    if "matrix" in filepath.name:
        adatas_matrix.append(adata)
    elif "counts" in filepath.name:
        adatas_counts.append(adata)
    else:
        raise ValueError(f"Unknown file type: {filepath}")

KeyboardInterrupt:

In [8]:
vars = [adata.var for adata in adatas_matrix]
for var in vars:
    assert var.index.is_unique
    assert np.all(var.index==vars[0].index)
    assert np.all(var==vars[0])

In [3]:
ad.experimental.concat_on_disk([filepath for filepath in sorted(list(lair.get_dataset_filepaths(ds).values())) if "matrix" in filepath.name], "matrix.h5ad", join="outer", fill_value=0)

OSError: Unable to synchronously open file (file signature not found)

In [24]:

adata_counts = ad.concat(adatas_counts, axis=0, join="outer")

/Users/halu/Code/tme_analysis/.venv/lib/python3.14/site-packages/anndata/_core/merge.py:643: FutureWarning: pd.api.extensions.take accepting non-standard inputs is deprecated and will raise in a future version. Pass either a numpy.ndarray, ExtensionArray, Index, or Series instead.
  return pd.api.extensions.take(

AttributeError: 'Dataset' object has no attribute 'take'

In [19]:
for adata in adatas_counts:
    print(adata.shape)

(2023, 16346)
(2353, 16424)
(2993, 15310)
(1441, 14430)
(2042, 16254)
(2385, 16357)
(1589, 13385)
(1528, 12851)
(1542, 13808)
(2244, 15125)
(1774, 15013)
(2043, 15041)
(1575, 14020)
(1282, 13977)
(1206, 14158)
(742, 12188)
(1115, 16834)
(982, 15304)
(1303, 16185)
(1361, 16262)
(1408, 16104)
(1950, 17163)
(708, 12274)
(2480, 21118)
(2942, 24575)
(2229, 23994)
(402, 11239)
(2193, 20689)
(652, 12101)
(2306, 17770)
(3349, 21107)
(3057, 21087)
(3097, 19662)
(2949, 20480)
(3659, 20874)
(1759, 17825)
(1643, 21066)
(2481, 24579)
(2429, 23280)
(2619, 23835)
(2426, 22795)
(2052, 22825)
(1630, 18290)
(1732, 17692)
(1459, 17521)
(1538, 17429)
(479, 12502)
(815, 12737)
(3441, 20749)
(1168, 16962)
(1513, 17194)
(1649, 17776)
(270, 11976)
(772, 13019)
(632, 12343)
(587, 11846)

In [22]:
adatas_counts[0].var

Empty DataFrame
Columns: []
Index: [DPM1, SCYL3, FGR, CFH, FUCA2, GCLC, NFYA, NIPAL3, LAS1L, ENPP4, ANKIB1, KRIT1, RAD52, BAD, LAP3, CD99, MAD1L1, LASP1, SNX11, TMEM176A, M6PR, ICA1, DBNDD1, ALS2, CASP10, CFLAR, NDUFAF7, RBM5, ARF5, SARM1, POLDIP2, PLXND1, AK2, CD38, FKBP4, KDM1A, RBM6, CAMKK1, RECQL, CCDC132, ARHGAP33, NDUFAB1, PDK4, ARX, SLC25A13, ST7, CDC27, HCCS, DVL2, UPF1, SKAP2, SLC25A5, CCDC109B, POLR2J, DHX33, MEOX1, LIG3, RPAP3, ACSM3, AC004381.6, CIAPIN1, SPPL2B, FAM214B, COPZ2, PRKAR2B, MSL3, CREBBP, BZRAP1, MPO, GCFC2, WDR54, CROT, ABCB4, KMT2E, RHBDD2, SOX8, IBTK, ZNF195, MYCBP2, FBXL3, ITGAL, PDK2, ITGA3, ZFX, LAMP2, GDE1, C19ORF60, CRLF1, OSBPL7, MAP3K14, TMEM132A, AP2B1, ZNF263, SPATA20, TNFRSF12A, MAP3K9, RALA, KDM7A, AGK, ALDH3B1, ...]

[16346 rows x 0 columns]

In [ ]:
rng = np.random.default_rng(seed=42)
adata = ad.read_h5ad(, backed="r")
print(adata.n_obs)
selection = rng.choice(adata.obs.index, size=10, replace=False)
adata = adata[selection].to_memory()

In [83]:
ensembl = pyensembl.EnsemblRelease(release=111, species="human")
detect_pre_id_transform(adata.var_names, ensembl=ensembl)

'hugo'

In [84]:
var_hugo = normalize_all_genes(adata.var_names, pre_id_transform="hugo")
var_auto = normalize_all_genes(adata.var_names, pre_id_transform="auto")
var_none = normalize_all_genes(adata.var_names)

In [85]:
print(var_hugo.shape)
print(var_auto.shape)
print(var_none.shape)

(70563, 10)
(70563, 10)
(70563, 10)

In [86]:
print(var_hugo.dropna().shape)
print(var_auto.dropna().shape)
print(var_none.dropna().shape)

(23158, 10)
(23158, 10)
(32822, 10)

In [87]:
np.all(var_auto.dropna()["original.id"]==var_hugo.dropna()["original.id"])

np.True_

In [90]:
var_auto

,original.id,contig,start,end,strand,biotype,gene_id,gene_name,EnsemblRelease.release,EnsemblRelease.species
0,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A1BG,19,58345178,58353492,-,protein_coding,ENSG00000121410,A1BG,111,homo_sapiens
3,A1BG-AS1,19,58347718,58355455,+,lncRNA,ENSG00000268895,A1BG-AS1,111,homo_sapiens
4,A1CF,10,50799409,50885675,-,protein_coding,ENSG00000148584,A1CF,111,homo_sapiens
...,...,...,...,...,...,...,...,...,...,...
70558,ZYG11A,1,52842511,52894998,+,protein_coding,ENSG00000203995,ZYG11A,111,homo_sapiens
70559,ZYG11B,1,52726453,52827336,+,protein_coding,ENSG00000162378,ZYG11B,111,homo_sapiens
70560,ZYX,7,143381295,143391111,+,protein_coding,ENSG00000159840,ZYX,111,homo_sapiens
70561,ZZEF1,17,4004445,4143030,-,protein_coding,ENSG00000074755,ZZEF1,111,homo_sapiens
70562,ZZZ3,1,77562416,77683419,-,protein_coding,ENSG00000036549,ZZZ3,111,homo_sapiens

In [92]:
var_none.dropna()

,original.id,contig,start,end,strand,biotype,gene_id,gene_name,EnsemblRelease.release,EnsemblRelease.species
9172,ENSG00000000003,X,100627108,100639991,-,protein_coding,ENSG00000000003,TSPAN6,111,homo_sapiens
9173,ENSG00000000005,X,100584936,100599885,+,protein_coding,ENSG00000000005,TNMD,111,homo_sapiens
9174,ENSG00000000419,20,50934867,50959140,-,protein_coding,ENSG00000000419,DPM1,111,homo_sapiens
9175,ENSG00000000457,1,169849631,169894267,-,protein_coding,ENSG00000000457,SCYL3,111,homo_sapiens
9176,ENSG00000000460,1,169662007,169854080,+,protein_coding,ENSG00000000460,FIRRM,111,homo_sapiens
...,...,...,...,...,...,...,...,...,...,...
42861,ENSG00000283096,10,78176928,78178186,+,lncRNA,ENSG00000283096,,111,homo_sapiens
42862,ENSG00000283103,19,58309727,58327252,-,lncRNA,ENSG00000283103,,111,homo_sapiens
42863,ENSG00000283117,7,10449820,10779944,-,lncRNA,ENSG00000283117,MGC4859,111,homo_sapiens
42864,ENSG00000283118,2,144444848,144450450,+,lncRNA,ENSG00000283118,,111,homo_sapiens
42865,ENSG00000283125,18,63207622,63208168,+,lncRNA,ENSG00000283125,,111,homo_sapiens

In [94]:
adata.var_names[9174]

'ENSG00000000419'